### ISSUE TITLE
Design Homepage

### ISSUE THREAD

**Issue by polarbearTW** [way-seoul/on-my-way#31]
Need to decide a style for our website

A mood board for website ideas: https://pin.it/53rURoO

Design Tools 
***Please log in with On My Way google account so we can all have the access to the design
-Canva (Design Tool): https://www.canva.com/
-Figma  (Design Tool): https://www.figma.com/

**Comment by LEMON4DE** [comment]
Created an account for each website!

**Comment by hjusassac** [comment]
https://www.canva.com/design/DAFZU4NdKJw/4aP8AifoYx5orS9J8UKyfA/view?utm_content=DAFZU4NdKJw&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

On Canva, basic design is done.
Thanks Judy><
