### ISSUE TITLE
comments feature

### ISSUE THREAD

**Issue by hjusassac** [way-seoul/on-my-way#39]
Users can comment on each challenge.
Display username, content, created_time, accomplishment badge(if the commentor has accomplished the challenge when comment)

- [x] create table "comments" (design db structure)
- [x] list view
- [x] add comments
- [ ] edit comments(?)
- [x] delete comments

**Comment by Struanjh** [comment]
Will start to work on this. Error messages appear on the challenge-specific page, so will fix them first.

**Comment by Struanjh** [comment]
I've commited code for ADD, LIST, DELETE comments to the "challenge-comments" branch.
Not sure if EDIT is really needed...?

**Comment by Struanjh** [comment]
Please Note: for now the User is set statically to USER ID 1 (Hyeonju). Small modification to code will be required later to user can be selected dynamically

**Comment by hjusassac** [comment]
edit comments isn't necessary I think
