### ISSUE TITLE
add <on the spot> functionality on challenge specific page

### ISSUE THREAD

**Issue by hjusassac** [way-seoul/on-my-way#44]
when the user clicks on the button [I'm ON THE SPOT!]

A: Get user's current location coordinates
B: Get the location coordinates of the specific challenge

Match A and B: define how much distance should be considered as <on the spot>

-> if true, 
    1. user gets the challenge point
    2. modal pops up and show: the number of users who've accomplished the challenge, ..., congrats lines and effects
    3. disable the button -> show what instead..?

-> else, 
    1. nothing..?

**Comment by Struanjh** [comment]
I will start working on the code to get user co-ordinates and compare to place co-ordinates

**Comment by Struanjh** [comment]
This functionality is completed, please check code is okay
