### ISSUE TITLE
[bug] delete user not working

### ISSUE THREAD

**Issue by hjusassac** [way-seoul/on-my-way#91]
probably related to #87 (html structure modified on adminView.php)

**Comment by polarbearTW** [comment]
@hjusassac I just checked~! It's because you didn't add back the class "delete-user" when re-making the admin table!
I will add it in my next pull-request along with google login thing, so it will be fixed:)

**Comment by hjusassac** [comment]
Oh! Thanks for checking! bbb @polarbearTW

**Comment by hjusassac** [comment]
no prob with the latest sql
